image: ubuntu:latest

build-x86_64:
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  before_script:
    - apt-get update
    - apt-get install -y build-essential pkg-config uuid-dev
  script:
    - make
